name:               hyperbole
version:            0.4.2
synopsis:           Interactive HTML apps using type-safe serverside Haskell
homepage:           https://github.com/seanhess/hyperbole
github:             seanhess/hyperbole
license:            BSD-3-Clause
license-file:       LICENSE
author:             Sean Hess
maintainer:         seanhess@gmail.com
category:           Web, Network
description:        Interactive HTML applications using type-safe serverside Haskell. Inspired by HTMX, Elm, and Phoenix LiveView

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - client/dist/hyperbole.js

language: GHC2021

ghc-options:
  - -Wall
  - -fdefer-typed-holes

tested-with:
  - GHC == 9.8.2
  - GHC == 9.6.6

default-extensions:
  - OverloadedStrings
  - OverloadedRecordDot
  - DuplicateRecordFields
  - NoFieldSelectors
  - TypeFamilies
  - DataKinds
  - DerivingStrategies
  - DeriveAnyClass

dependencies:
  - base >=4.16 && <5
  - bytestring >= 0.11 && <0.13
  - containers >= 0.6 && <1
  - casing > 0.1 && <0.2
  - effectful >= 2.4 && <3
  - text >= 1.2 && <3
  - string-interpolate >= 0.3 && <0.4
  - file-embed >= 0.0.10 && <0.1
  - http-api-data >= 0.6 && <0.7
  - http-types >= 0.12 && <0.13
  - wai >= 3.2 && <4
  - warp >= 3.3 && <4
  - web-view >= 0.6 && <= 1.0
  - string-conversions >= 0.4 && <0.5
  - wai-websockets >= 3.0 && <4
  - network >= 3.1 && <4
  - websockets >= 0.12 && <0.14
  - cookie >=0.4 && <0.5

library:
  source-dirs: src

tests:
  test:
    main:        Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -F -pgmF=skeletest-preprocessor
    dependencies:
      - hyperbole
      - Diff >= 0.5 && <1.0
      - skeletest



