name:               docgen
version:            0.1
synopsis:           Generate Inline Documentation Examples for Hyperbole
homepage:           https://github.com/seanhess/hyperbole
github:             seanhess/hyperbole
license:            BSD-3-Clause
author:             Sean Hess
maintainer:         seanhess@gmail.com
category:           Web, Network

language: GHC2021

ghc-options:
  - -Wall
  - -fdefer-typed-holes

default-extensions:
  - OverloadedStrings
  - OverloadedRecordDot
  - DuplicateRecordFields
  - NoFieldSelectors
  - TypeFamilies
  - DataKinds
  - DerivingStrategies
  - DeriveAnyClass

dependencies:
  - base
  - text
  - directory
  - filepath
  - string-conversions

executables:
  docgen:
    main:                Main.hs
    source-dirs:
      - ./src
    dependencies: []
