name:               docgen
version:            0.4.3
synopsis:           Interactive HTML apps using type-safe serverside Haskell
homepage:           https://github.com/seanhess/hyperbole
github:             seanhess/hyperbole
license:            BSD-3-Clause
author:             Sean Hess
maintainer:         seanhess@gmail.com
category:           Web, Network
description:        Interactive HTML applications using type-safe serverside Haskell. Inspired by HTMX, Elm, and Phoenix LiveView

language: GHC2021

ghc-options:
  - -Wall
  - -fdefer-typed-holes

default-extensions:
  - OverloadedStrings
  - OverloadedRecordDot
  - DuplicateRecordFields
  - NoFieldSelectors
  - TypeFamilies
  - DataKinds
  - DerivingStrategies
  - DeriveAnyClass

dependencies:
  - base
  - directory
  - filepath
  - text
  - string-conversions

executables:
  docgen:
    main:                Main.hs
    source-dirs:
      - .
    dependencies: []

